# Generated by Django 4.2.29 on 2026-03-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('people', models.PositiveIntegerField(default=1)),
                ('days', models.PositiveIntegerField(default=1)),
                ('hotel_per_night', models.FloatField(default=0.0)),
                ('food_per_day', models.FloatField(default=0.0)),
                ('travel', models.FloatField(default=0.0)),
                ('activities', models.FloatField(default=0.0)),
                ('misc', models.FloatField(default=0.0)),
                ('contingency_pct', models.FloatField(default=0.0)),
                ('hotel_total', models.FloatField(default=0.0)),
                ('food_total', models.FloatField(default=0.0)),
                ('base_total', models.FloatField(default=0.0)),
                ('contingency', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('per_person', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
