# Generated by Django 4.2.29 on 2026-03-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_tripplan"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TripPlan",
        ),
    ]
