# Generated by Django 4.2.29 on 2026-03-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_delete_tripplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
