# Generated by Django 6.0.3 on 2026-03-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_alter_expense_amount_alter_settlement_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('people', models.PositiveIntegerField(default=1)),
                ('days', models.PositiveIntegerField(default=1)),
                ('hotel_per_night', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activities', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('misc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contingency_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hotel_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contingency', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('raw_query', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('desc', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
