# Generated by Django 4.2.29 on 2026-03-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_remove_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Food', 'Food'), ('Travel', 'Travel'), ('Activities', 'Activities'), ('Misc', 'Misc')], default='Misc', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
